<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Faker\Factory as Faker;
use Illuminate\Support\Str;

class MonAnSeeder extends Seeder
{
    public function run()
    {
        DB::table('mon_ans')->delete();
        DB::table('mon_ans')->truncate();

        // $faker = Faker::create();
        DB::table('mon_ans')->insert([
            [
                'ten_mon_an'       =>  'Đậu Phộng',
                'slug_mon_an'      =>  Str::slug('Đậu Phộng'),
                'gia_ban'       =>  random_int(5, 2000) * 1000,
                'tinh_trang'    =>  random_int(0, 1),
                'id_danh_muc'   =>  1,
                'updated_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'ten_mon_an'       =>  'Khoai Tây Chiên',
                'slug_mon_an'      =>  Str::slug('Khoai Tây Chiên'),
                'gia_ban'       =>  random_int(5, 2000) * 1000,
                'tinh_trang'    =>  random_int(0, 1),
                'id_danh_muc'   =>  1,
                'updated_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'ten_mon_an'       =>  'Đậu Khuôn Lướt Ván',
                'slug_mon_an'      =>  Str::slug('Đậu Khuôn Lướt Ván'),
                'gia_ban'       =>  random_int(5, 2000) * 1000,
                'tinh_trang'    =>  random_int(0, 1),
                'id_danh_muc'   =>  1,
                'updated_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'ten_mon_an'       =>  'Tôm Đất Rang Muối',
                'slug_mon_an'      =>  Str::slug('Tôm Đất Rang Muối'),
                'gia_ban'       =>  random_int(5, 2000) * 1000,
                'tinh_trang'    =>  random_int(0, 1),
                'id_danh_muc'   =>  1,
                'updated_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'ten_mon_an'       =>  'Cơm Chiên Trứng',
                'slug_mon_an'      =>  Str::slug('Cơm Chiên Trứng'),
                'gia_ban'       =>  random_int(5, 2000) * 1000,
                'tinh_trang'    =>  random_int(0, 1),
                'id_danh_muc'   =>  5,
                'updated_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'ten_mon_an'       =>  'Hàu nướng',
                'slug_mon_an'      =>  Str::slug('Hàu nướng'),
                'gia_ban'       =>  random_int(5, 2000) * 1000,
                'tinh_trang'    =>  random_int(0, 1),
                'id_danh_muc'   =>  4,
                'updated_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'ten_mon_an'       =>  'Sò huyết nướng',
                'slug_mon_an'      =>  Str::slug('Sò huyết nướng'),
                'gia_ban'       =>  random_int(5, 2000) * 1000,
                'tinh_trang'    =>  random_int(0, 1),
                'id_danh_muc'   =>  4,
                'updated_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'ten_mon_an'       =>  'Mực nhồi thịt',
                'slug_mon_an'      =>  Str::slug('Mực nhồi thịt'),
                'gia_ban'       =>  random_int(5, 2000) * 1000,
                'tinh_trang'    =>  random_int(0, 1),
                'id_danh_muc'   =>  4,
                'updated_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'ten_mon_an'       =>  'Bào ngư xào sả ớt',
                'slug_mon_an'      =>  Str::slug('Bào ngư xào sả ớt'),
                'gia_ban'       =>  random_int(5, 2000) * 1000,
                'tinh_trang'    =>  random_int(0, 1),
                'id_danh_muc'   =>  4,
                'updated_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'ten_mon_an'       =>  'Cơm Chiên Hải Sản',
                'slug_mon_an'      =>  Str::slug('Cơm Chiên Hải Sản'),
                'gia_ban'       =>  random_int(5, 2000) * 1000,
                'tinh_trang'    =>  random_int(0, 1),
                'id_danh_muc'   =>  5,
                'updated_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'ten_mon_an'       =>  'Cơm Chiên Dương Châu',
                'slug_mon_an'      =>  Str::slug('Cơm Chiên Dương Châu'),
                'gia_ban'       =>  random_int(5, 2000) * 1000,
                'tinh_trang'    =>  random_int(0, 1),
                'id_danh_muc'   =>  5,
                'updated_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'ten_mon_an'       =>  'Cá Chiên Giòn',
                'slug_mon_an'      =>  Str::slug('Cá Chiên Giòn'),
                'gia_ban'       =>  random_int(5, 2000) * 1000,
                'tinh_trang'    =>  random_int(0, 1),
                'id_danh_muc'   =>  5,
                'updated_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'ten_mon_an'       =>  'Thịt xào rau củ',
                'slug_mon_an'      =>  Str::slug('Thịt xào rau củ'),
                'gia_ban'       =>  random_int(5, 2000) * 1000,
                'tinh_trang'    =>  random_int(0, 1),
                'id_danh_muc'   =>  5,
                'updated_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'ten_mon_an'       =>  'Cải Xào Tỏi',
                'slug_mon_an'      =>  Str::slug('Cải xào tỏi'),
                'gia_ban'       =>  random_int(5, 2000) * 1000,
                'tinh_trang'    =>  random_int(0, 1),
                'id_danh_muc'   =>  5,
                'updated_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'ten_mon_an'       =>  'Mì Xào Hải Sản',
                'slug_mon_an'      =>  Str::slug('Mì xào Hải Sản'),
                'gia_ban'       =>  random_int(5, 2000) * 1000,
                'tinh_trang'    =>  random_int(0, 1),
                'id_danh_muc'   =>  5,
                'updated_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'ten_mon_an'       =>  'Gỏi Sứa',
                'slug_mon_an'      =>  Str::slug('Gỏi Sứa'),
                'gia_ban'       =>  random_int(5, 2000) * 1000,
                'tinh_trang'    =>  random_int(0, 1),
                'id_danh_muc'   =>  2,
                'updated_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'ten_mon_an'       =>  'Gỏi Đu Đủ',
                'slug_mon_an'      =>  Str::slug('Gỏi Đu Đủ'),
                'gia_ban'       =>  random_int(5, 2000) * 1000,
                'tinh_trang'    =>  random_int(0, 1),
                'id_danh_muc'   =>  2,
                'updated_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'ten_mon_an'       =>  'Salad Trộn Gà',
                'slug_mon_an'      =>  Str::slug('Salad Trộn Gà'),
                'gia_ban'       =>  random_int(5, 2000) * 1000,
                'tinh_trang'    =>  random_int(0, 1),
                'id_danh_muc'   =>  2,
                'updated_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'ten_mon_an'       =>  'Gỏi Bò',
                'slug_mon_an'      =>  Str::slug('Gỏi Bò'),
                'gia_ban'       =>  random_int(5, 2000) * 1000,
                'tinh_trang'    =>  random_int(0, 1),
                'id_danh_muc'   =>  2,
                'updated_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'ten_mon_an'       =>  'Salad Cá Ngừ',
                'slug_mon_an'      =>  Str::slug('Salad Cá Ngừ'),
                'gia_ban'       =>  random_int(5, 2000) * 1000,
                'tinh_trang'    =>  random_int(0, 1),
                'id_danh_muc'   =>  2,
                'updated_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'ten_mon_an'       =>  'Lẩu Bò',
                'slug_mon_an'      =>  Str::slug('Lẩu Bò'),
                'gia_ban'       =>  random_int(5, 2000) * 1000,
                'tinh_trang'    =>  random_int(0, 1),
                'id_danh_muc'   =>  6,
                'updated_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'ten_mon_an'       =>  'Lẩu Cá Kèo',
                'slug_mon_an'      =>  Str::slug('Lẩu Cá Kèo'),
                'gia_ban'       =>  random_int(5, 2000) * 1000,
                'tinh_trang'    =>  random_int(0, 1),
                'id_danh_muc'   =>  6,
                'updated_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'ten_mon_an'       =>  'Lẩu Dấm',
                'slug_mon_an'      =>  Str::slug('Lẩu Dấm'),
                'gia_ban'       =>  random_int(5, 2000) * 1000,
                'tinh_trang'    =>  random_int(0, 1),
                'id_danh_muc'   =>  6,
                'updated_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'ten_mon_an'       =>  'Lẩu Nắm',
                'slug_mon_an'      =>  Str::slug('Lẩu Nắm'),
                'gia_ban'       =>  random_int(5, 2000) * 1000,
                'tinh_trang'    =>  random_int(0, 1),
                'id_danh_muc'   =>  6,
                'updated_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'ten_mon_an'       =>  'Lẩu Thái',
                'slug_mon_an'      =>  Str::slug('Lẩu Thái'),
                'gia_ban'       =>  random_int(5, 2000) * 1000,
                'tinh_trang'    =>  random_int(0, 1),
                'id_danh_muc'   =>  6,
                'updated_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'ten_mon_an'       =>  'Lẩu Thập Cẩm',
                'slug_mon_an'      =>  Str::slug('Lẩu Thập Cẩm'),
                'gia_ban'       =>  random_int(5, 2000) * 1000,
                'tinh_trang'    =>  random_int(0, 1),
                'id_danh_muc'   =>  6,
                'updated_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'ten_mon_an'       =>  'Lẩu Cá Ngừ',
                'slug_mon_an'      =>  Str::slug('Lẩu Cá Ngừ'),
                'gia_ban'       =>  random_int(5, 2000) * 1000,
                'tinh_trang'    =>  random_int(0, 1),
                'id_danh_muc'   =>  6,
                'updated_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'ten_mon_an'       =>  'Lẩu Chay',
                'slug_mon_an'      =>  Str::slug('Lẩu Chay'),
                'gia_ban'       =>  random_int(5, 2000) * 1000,
                'tinh_trang'    =>  random_int(0, 1),
                'id_danh_muc'   =>  6,
                'updated_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'ten_mon_an'       =>  'Bò Nhúng Ớt',
                'slug_mon_an'      =>  Str::slug('Bò Nhúng Ớt'),
                'gia_ban'       =>  random_int(5, 2000) * 1000,
                'tinh_trang'    =>  random_int(0, 1),
                'id_danh_muc'   =>  7,
                'updated_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'ten_mon_an'       =>  'Rau Muống',
                'slug_mon_an'      =>  Str::slug('Rau Muống'),
                'gia_ban'       =>  random_int(5, 2000) * 1000,
                'tinh_trang'    =>  random_int(0, 1),
                'id_danh_muc'   =>  9,
                'updated_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'ten_mon_an'       =>  'Ba Chỉ Thịt Heo',
                'slug_mon_an'      =>  Str::slug('Ba Chỉ Thịt Heo'),
                'gia_ban'       =>  random_int(5, 2000) * 1000,
                'tinh_trang'    =>  random_int(0, 1),
                'id_danh_muc'   =>  9,
                'updated_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'ten_mon_an'       =>  'Rau Cải',
                'slug_mon_an'      =>  Str::slug('Rau Cải'),
                'gia_ban'       =>  random_int(5, 2000) * 1000,
                'tinh_trang'    =>  random_int(0, 1),
                'id_danh_muc'   =>  9,
                'updated_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'ten_mon_an'       =>  'Bún',
                'slug_mon_an'      =>  Str::slug('Bún'),
                'gia_ban'       =>  random_int(5, 2000) * 1000,
                'tinh_trang'    =>  random_int(0, 1),
                'id_danh_muc'   =>  9,
                'updated_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'ten_mon_an'       =>  'Bánh Tráng',
                'slug_mon_an'      =>  Str::slug('Bánh Tráng'),
                'gia_ban'       =>  random_int(5, 2000) * 1000,
                'tinh_trang'    =>  random_int(0, 1),
                'id_danh_muc'   =>  9,
                'updated_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'ten_mon_an'       =>  'Đậu Hũ',
                'slug_mon_an'      =>  Str::slug('Đậu Hũ'),
                'gia_ban'       =>  random_int(5, 2000) * 1000,
                'tinh_trang'    =>  random_int(0, 1),
                'id_danh_muc'   =>  9,
                'updated_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'ten_mon_an'       =>  'Bánh Mỳ',
                'slug_mon_an'      =>  Str::slug('Bánh Mỳ'),
                'gia_ban'       =>  random_int(5, 2000) * 1000,
                'tinh_trang'    =>  random_int(0, 1),
                'id_danh_muc'   =>  9,
                'updated_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'ten_mon_an'       =>  'Coca Cola',
                'slug_mon_an'      =>  Str::slug('Coca Cola'),
                'gia_ban'       =>  random_int(5, 2000) * 1000,
                'tinh_trang'    =>  random_int(0, 1),
                'id_danh_muc'   =>  8,
                'updated_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'ten_mon_an'       =>  'Pepsi',
                'slug_mon_an'      =>  Str::slug('Pepsi'),
                'gia_ban'       =>  random_int(5, 2000) * 1000,
                'tinh_trang'    =>  random_int(0, 1),
                'id_danh_muc'   =>  8,
                'updated_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'ten_mon_an'       =>  'Fanta',
                'slug_mon_an'      =>  Str::slug('Fanta'),
                'gia_ban'       =>  random_int(5, 2000) * 1000,
                'tinh_trang'    =>  random_int(0, 1),
                'id_danh_muc'   =>  8,
                'updated_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'ten_mon_an'       =>  'Sting',
                'slug_mon_an'      =>  Str::slug('Sting'),
                'gia_ban'       =>  random_int(5, 2000) * 1000,
                'tinh_trang'    =>  random_int(0, 1),
                'id_danh_muc'   =>  8,
                'updated_at'    => date('Y-m-d H:i:s'),
            ],
        ]);
    }
}
